import { StyleSheet } from "react-native";
import { Colors, isDarkMode, Sizes } from "./AppThems";

const Styles = StyleSheet.create({
    Container:{ flex:1, padding:Sizes.padding1 },
    Center:{ justifyContent:'center', },
    padding:{ paddingHorizontal: Sizes.padding1, paddingTop:Sizes.padding3},
    AppContainer:{ flex:1, backgroundColor:Colors.appColor, justifyContent:'center', alignItems:'center' },
    flex:{flexDirection:'row', justifyContent:'space-between', alignItems:'center'},
    icon: { width:'60%', height:80 },
    icon2: { width:200, height:80 },
    icon3: { width:50, height:75 },
    img:{ paddingBottom:30, flexDirection:'row', justifyContent:'center', alignItems:'center'},
    view1: { paddingHorizontal:Sizes.padding1, alignSelf:'flex-start'},
    txt1: { fontSize:Sizes.f1, fontWeight:'500',  },
    txt2: { fontSize:Sizes.f3, color:Colors.lightDirk, fontWeight:'500',  },
    txt3: { fontSize:15.5,  },
    txt5: { fontSize:Sizes.f3, color:Colors.white, fontWeight:'bold',  },
    productCard: {
      width: 170,
      marginRight: 16,
      borderRadius: Sizes.radius,
      backgroundColor: isDarkMode ? Colors.primary2 : Colors.lightGray,
    },
    productImage: {
      width: '100%',
      height: 200,
      borderRadius: 8,
      marginBottom: 8,
    },
    productName: {
      fontSize: Sizes.f5,
      paddingHorizontal: Sizes.padding3,    
    },
    productPrice: {
      fontSize: Sizes.f4,
      paddingHorizontal: Sizes.padding3,
      fontWeight: '600',
      marginBottom: Sizes.padding1,
      marginTop: Sizes.base,
    },
    section: {
      padding: 16,
    },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingBottom: Sizes.padding3,
      marginBottom: Sizes.padding2,
    },
    sectionTitle: {
      fontSize: Sizes.f3,
      fontWeight: '600',
    },
    seeAll: {
      fontSize: Sizes.f4,
      fontWeight: '500',
      color: '#6E3AFA',
    },
    logo: {
        alignSelf: 'center',
        marginBottom: 40,
      },
      input: {
        backgroundColor: Colors.lightGray,
        borderRadius: Sizes.radius,
        padding: Sizes.padding2,
        marginBottom: 16,
      },
      button: {
        backgroundColor: Colors.appColor,
        borderRadius: 30,
        padding: Sizes.padding2,
        alignItems: 'center',
        marginVertical: Sizes.padding2,
      },
      buttonText: {
        color: Colors.white,
        fontSize: Sizes.f3,
        fontWeight: '600',
      },
      googleButton: {
        backgroundColor: isDarkMode ? Colors.primary2 : Colors.lightGray,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: Colors.lightWhite2,
        borderRadius: 30,
        padding: Sizes.padding2,
        marginVertical: Sizes.padding3,
      },
      googleIcon: {
        width: 24,

        height: 24,
        marginRight: 8,
      },
      googleButtonText: {
        fontSize: Sizes.f3,
        fontWeight: '600',
      },
      linkText: {
        textAlign: 'left',
        fontSize: Sizes.f4,
        fontWeight: '500',
        },
      // font1:{fontSize:Sizes.f1, },
      // font2:{fontSize:Sizes.f2, },
      // font3:{fontSize:Sizes.f3, },
      // font4:{fontSize:Sizes.f4, },
      // font5:{fontSize:Sizes.f5, },
    border:{borderWidth:0.5, borderColor:Colors.gray},
    // btn: { padding:Sizes.padding3, borderRadius:Sizes.radius, alignItems:'center', marginVertical:Sizes.padding1},
    btn: {flexDirection:'row', alignItems:'center', gap: Sizes.padding1, padding: Sizes.padding2, backgroundColor: isDarkMode ? Colors.primary2 : Colors.lightGray, borderRadius: 10, marginBottom: Sizes.padding1},
    btn1: { backgroundColor: Colors.green, padding:13, borderRadius:Sizes.radius, alignItems:'center', marginRight:Sizes.padding2, marginTop: Sizes.padding2},
     btn2: {flexDirection:'row', alignItems:'center', gap: Sizes.padding2,backgroundColor:Colors.gray3, borderRadius: 30, padding: Sizes.padding2, paddingLeft: Sizes.large},    
    btn3: {flexDirection:'row', alignItems:'center', marginVertical:Sizes.padding1 ,gap: Sizes.padding2,backgroundColor:Colors.gray3, borderRadius: 30, padding: Sizes.padding2, paddingLeft: Sizes.large},
    header: {justifyContent:'center',alignItems:'center' },
    username: {fontSize: Sizes.f2 },
    email: {fontSize: Sizes.f3 },
    redio:{ width: 24,height: 24,borderRadius: 12,borderWidth: 2,borderColor: 'black',justifyContent: 'center',alignItems: 'center',marginRight: 8,},
    redioAnimation:{ width: 12,height: 12,borderRadius: 6,backgroundColor: 'black', },
    card:{ backgroundColor:'#212b35', borderRadius: 15, flexDirection:'row', paddingVertical: Sizes.padding2, alignItems:'center', marginTop:Sizes.padding2,justifyContent:'space-between', paddingHorizontal:Sizes.padding3 },
    card2:{ backgroundColor:'#212b35', borderRadius: 15, paddingVertical: Sizes.padding1, paddingLeft:Sizes.padding1, paddingBottom: Sizes.padding1 , marginTop:Sizes.padding1 },
    cardTitle: { fontSize: Sizes.f3, paddingBottom: Sizes.padding2 },
    cardSubTitle: { fontSize: Sizes.f4, paddingBottom: Sizes.padding2, marginLeft: Sizes.base },
    cardprice: { fontSize: Sizes.f1 },
    modle:{position: 'absolute', top: '100%', left: 0, right: 0,backgroundColor: '#384551', zIndex: 10, },
    upload:{padding:Sizes.padding1, alignItems:'center', backgroundColor:'#222730', borderRadius:10, borderWidth:1, borderStyle:'dashed', borderColor:Colors.gray, margin: Sizes.padding1},
    upload2:{padding:Sizes.padding1, alignItems:'center', backgroundColor:'#26313a', borderRadius:10, borderWidth:1, borderStyle:'dashed', borderColor:Colors.gray, marginVertical: Sizes.padding1},
    keybord:{ flex:1, justifyContent: 'center', paddingHorizontal: 16},
    innerKeybord:{ flex:1, justifyContent: 'center'},
    project:{fontSize:Sizes.f6, color:Colors.lightWhite, paddingTop:Sizes.padding1 ,paddingVertical:Sizes.base ,borderBottomWidth:2, borderColor: Colors.gray},
});

export default Styles;